"""
Anime-style renderer — same interface as viz.py, different sprite set.

This is the "prod mode" sister of viz.py. The env core produces state
trajectories; this module consumes them with a chibi clownfish sprite set
generated by scripts/make_anime_sprite.py. Zero changes to env.py.

Design contract: dev viz and anime viz read the same EnvState and produce
renders with the same positional coordinates. Swapping one for the other
is a one-line import change.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.animation as animation
import matplotlib.pyplot as plt
from matplotlib.offsetbox import AnnotationBbox, OffsetImage
from matplotlib.patches import Circle
import numpy as np
from PIL import Image

from .env import EnvConfig, EnvState


_ASSETS = Path(__file__).resolve().parent.parent / "assets" / "anime"

_BG_COLOR = "#d9f2f7"      # pale aqua — water
_FOOD_COLOR = "#a0c8d4"    # plankton tint
_DEAD_ALPHA = 0.35

_N_ROT_BINS = 72


def _load(name: str) -> Image.Image:
    return Image.open(_ASSETS / name).convert("RGBA")


def _prerotate(img: Image.Image, n_bins: int) -> list[Image.Image]:
    return [
        img.rotate(i * 360.0 / n_bins, resample=Image.BICUBIC, expand=True)
        for i in range(n_bins)
    ]


def _faded(img: Image.Image, alpha: float) -> Image.Image:
    arr = np.array(img)
    arr[..., 3] = (arr[..., 3].astype(np.float32) * alpha).astype(np.uint8)
    return Image.fromarray(arr)


# Load sprite masters once
try:
    _DEFAULT_SRC = _load("fish_default.png")
    _LEADER_SRC = _load("fish_leader.png")
    _PRED_SRC = _load("predator.png")
except FileNotFoundError as e:
    raise FileNotFoundError(
        "anime sprites missing. Run `uv run python scripts/make_anime_sprite.py`"
    ) from e

_DEAD_SRC = _faded(_DEFAULT_SRC, _DEAD_ALPHA)

_DEFAULT_ROT = _prerotate(_DEFAULT_SRC, _N_ROT_BINS)
_LEADER_ROT = _prerotate(_LEADER_SRC, _N_ROT_BINS)
_DEAD_ROT = _prerotate(_DEAD_SRC, _N_ROT_BINS)
_PRED_ROT = _prerotate(_PRED_SRC, _N_ROT_BINS)


def _sprite_for_angle(cache: list[Image.Image], angle_rad: float) -> np.ndarray:
    deg = np.degrees(angle_rad) % 360.0
    idx = int(round(deg / (360.0 / _N_ROT_BINS))) % _N_ROT_BINS
    return np.asarray(cache[idx])


def _draw_water_background(ax, cfg: EnvConfig) -> None:
    """Subtle caustic-like gradient to suggest water depth."""
    # pale gradient overlay via imshow
    grad = np.linspace(0.0, 1.0, 128)[:, None] * np.ones(128)
    ax.imshow(
        grad,
        extent=(0, cfg.world_size, 0, cfg.world_size),
        cmap="Blues",
        alpha=0.12,
        origin="lower",
        zorder=0,
    )


def _setup_axes(ax, cfg: EnvConfig) -> None:
    ax.set_xlim(0, cfg.world_size)
    ax.set_ylim(0, cfg.world_size)
    ax.set_aspect("equal")
    ax.set_facecolor(_BG_COLOR)
    ax.set_xticks([])
    ax.set_yticks([])
    for spine in ax.spines.values():
        spine.set_visible(False)


def _place(ax, sprite: np.ndarray, x: float, y: float, zoom: float) -> None:
    im = OffsetImage(sprite, zoom=zoom, interpolation="bilinear")
    ab = AnnotationBbox(
        im, (x, y),
        frameon=False, pad=0.0,
        box_alignment=(0.5, 0.5),
        bboxprops=dict(edgecolor="none", facecolor="none", linewidth=0),
    )
    ax.add_artist(ab)


def draw_frame(
    ax,
    state: EnvState,
    cfg: EnvConfig,
    *,
    leader_idx: int | None = None,
    fish_zoom: float = 0.035,
    pred_zoom: float = 0.055,
) -> None:
    """Render one anime-style frame into an axes."""
    ax.clear()
    _setup_axes(ax, cfg)
    _draw_water_background(ax, cfg)

    pos = np.asarray(state.fish_pos)
    vel = np.asarray(state.fish_vel)
    alive = np.asarray(state.fish_alive)

    # food first (plankton particles)
    food_pos = np.asarray(state.food_pos)
    food_active = np.asarray(state.food_active)
    for (fx, fy), active in zip(food_pos, food_active):
        if active:
            ax.add_patch(Circle((fx, fy), 0.55, color=_FOOD_COLOR, zorder=1, alpha=0.8))

    # fish
    for i in range(cfg.n_fish):
        ang = float(np.arctan2(vel[i, 1], vel[i, 0]))
        if not alive[i]:
            cache = _DEAD_ROT
        elif leader_idx is not None and i == leader_idx:
            cache = _LEADER_ROT
        else:
            cache = _DEFAULT_ROT
        sprite = _sprite_for_angle(cache, ang)
        _place(ax, sprite, float(pos[i, 0]), float(pos[i, 1]), fish_zoom)

    # predators
    pred_pos = np.asarray(state.pred_pos)
    pred_vel = np.asarray(state.pred_vel)
    for i in range(cfg.n_predators):
        ang = float(np.arctan2(pred_vel[i, 1], pred_vel[i, 0]))
        sprite = _sprite_for_angle(_PRED_ROT, ang)
        _place(ax, sprite, float(pred_pos[i, 0]), float(pred_pos[i, 1]), pred_zoom)


def render_gif(
    states: list[EnvState],
    cfg: EnvConfig,
    out_path: str,
    *,
    fps: int = 24,
    figsize: tuple[float, float] = (7, 7),
    dpi: int = 100,
    leader_fn=None,
) -> None:
    fig, ax = plt.subplots(figsize=figsize, dpi=dpi)

    def _draw(i):
        leader = leader_fn(states[i], i) if leader_fn is not None else None
        draw_frame(ax, states[i], cfg, leader_idx=leader)
        return []

    anim = animation.FuncAnimation(
        fig, _draw, frames=len(states), interval=1000 / fps, blit=False
    )
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    anim.save(
        out_path, writer="pillow", fps=fps, dpi=dpi,
        savefig_kwargs={"facecolor": _BG_COLOR},
    )
    plt.close(fig)
